### ISSUE TITLE
Running exiftool with the subprocess module

### ISSUE THREAD

**Issue by helenabdr** [exiftool/exiftool#60]
The problem is when I pass the newly created path instead of the original image path to the ***get_embedded*** function. But I need of new path, I don't know what to do, any suggestion? Thanks ;)

Code:
```
import io
from PIL import Image
import subprocess
import pathlib
import cv2

im1 = Image.open(pathlib.Path('input/FLIR2705.jpg'))  

im1 = im1.save('geeks.jpg')
print(im1)

def get_embedded(path):

    img_bytes = subprocess.check_output([
        "exiftool", "-EmbeddedImage", "-b", path
    ])

    print(type(img_bytes))

    img_stream = io.BytesIO(img_bytes)

    #print(img_stream.read())
    img = Image.open(img_stream)

    print(img)
    return img

get_embedded('geeks.jpg')

```
Error:
```
Traceback (most recent call last):
  File "/home/helena/Documents/LAR_Celesc/robocelesc_backend/w.py", line 39, in <module>
    get_embedded('geeks.jpg')
  File "/home/helena/Documents/LAR_Celesc/robocelesc_backend/w.py", line 34, in get_embedded
    img = Image.open(img_stream)
  File "/home/helena/Documents/LAR_Celesc/robocelesc_backend/fenv/lib/python3.7/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f28a1f23f50>
```

**Comment by boardhead** [comment]
This seems to be a question about a Python interface for ExifTool, which is a different project.
